[package]
org = "ballerina"
name = "email"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "./lib/javax.mail-1.6.2.jar"

[[platform.java11.dependency]]
path = "./lib/greenmail-1.5.11.jar"

[[platform.java11.dependency]]
path = "./lib/mimepull-1.9.11.jar"

[[platform.java11.dependency]]
path = "./lib/testng-7.4.0.jar"

[[platform.java11.dependency]]
path = "../native/build/libs/email-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/email-test-utils-@project.version@.jar"
scope = "testOnly"
