[package]
org = "ballerina"
name = "email"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "./lib/jakarta.mail-2.0.1.jar"
groupId = "com.sun.mail"
artifactId = "jakarta.mail"
version = "2.0.1"

[[platform.java11.dependency]]
path = "./lib/jakarta.activation-2.0.0.jar"
groupId = "com.sun.activation"
artifactId = "jakarta.activation"
version = "2.0.0"


[[platform.java11.dependency]]
path = "./lib/greenmail-2.0.0-alpha-1.jar"
groupId = "com.sun.mail"
artifactId = "greenmail"
version = "2.0.0-alpha-1"


[[platform.java11.dependency]]
path = "./lib/mimepull-1.9.11.jar"
groupId = "org.jvnet.mimepull"
artifactId = "mimepull"
version = "1.9.11"


[[platform.java11.dependency]]
path = "./lib/testng-7.4.0.jar"
groupId = "org.testng"
artifactId = "testng"
version = "7.4.0"


[[platform.java11.dependency]]
path = "../email-native/build/libs/email-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "email"
version = "@project.version@"


[[platform.java11.dependency]]
path = "../email-test-utils/build/libs/email-test-utils-@project.version@.jar"
groupId = "org.ballerinalang.stdlib.email"
scope = "testOnly"
artifactId = "email"
version = "@project.version@"
