[plugin]
id = "email-compiler-plugin"
class = "io.ballerina.stdlib.email.compiler.EmailCompilerPlugin"

[[dependency]]
path = "../email-compiler-plugin/build/libs/email-compiler-plugin-@project.version@.jar"
