[[dependency]]
org = "ballerina"
name = "io"
version = "0.5.6"

[[dependency]]
org = "ballerina"
name = "time"
version = "1.0.7"

[[dependency]]
org = "ballerina"
name = "file"
version = "0.6.4"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.0.6"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.7.1"

[[dependency]]
org = "ballerina"
name = "task"
version = "1.1.6"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.0.6"
